### ISSUE TITLE
primewireag is now primewire.to

### ISSUE THREAD

**Issue by michaeldiemart** [piplongrun/lmwt-kiss.bundle#16]
custom url option does not work on the new url please modifý the addon and please add all of the links/sources from primewire it would be nice

**Comment by Twoure** [comment]
primewire.to is a _fake_ mirror _(yes it works online, but is not a one-to-one mirror of the official site)_, and does not work with this channel.  Refer to PrimeWire's official [Facebook](https://www.facebook.com/PrimeWire-684860298316669/about/?entry_point=about_section_header) page for the current _Site URL_.  The real PrimeWire page will show current official mirrors. The remaining _Site URLs_ (included in the channel's preferences) are current un-official one-to-one mirrors _(i.e. structured the same)_ of the original site.

Another user recently posted a [list](https://forums.plex.tv/discussion/comment/1282090/#Comment_1282090) of PrimeWire mirrors/proxies, which will be reviewed for usage with this channel at a later time.

In the meantime, to try a _Site URL_ other than the included variants, use the [Custom URL](https://forums.plex.tv/discussion/comment/1268621/#Comment_1268621) option within this channel's preferences.  Remember, not all mirrors are structured the same, thus they are not compatible with this channel.  There is also a know issue with OpenSSL in the Plex Framework, so some `https` sites cannot be accessed by Plex (ref [#1](https://forums.plex.tv/discussion/comment/980853/#Comment_980853), ref [#2](https://forums.plex.tv/discussion/comment/1210565/#Comment_1210565)).  Furthermore, many proxy sites require setting cookies, so in general proxy sites do not work without changing the channels source code to accommodate a specific proxy.  I did do some work with the g2g channel to be compatible with a couple of proxies ([ref](https://github.com/TehCrucible/G2Gfm.bundle/pull/15)).  In the future I may work at doing the same for this channel as well (pending @piplongrun's approval).
