### ISSUE TITLE
Remove offline links

### ISSUE THREAD

**Issue by pdille** [piplongrun/lmwt-kiss.bundle#5]
This is surely a complicated request, but it's quite annoying to see a list of available streams only to discover that every single one is pointing to a dead link.

Are removing these dead links feasible with the way this plugin is structured and hooks into Plex?

I'm not adverse to getting my hands dirty in other people's code, so any pointers or comments in regards to this is most welcome.

And thanks for making this. Your work is most appreciated.

**Comment by Twoure** [comment]
> Are removing these dead links feasible with the way this plugin is structured and hooks into Plex?

Unfortunately the PrimeWire site is slow to remove offline links, and does not indicate if a link is bad.  The only way to check the links is to query each and test the retrieved video stream.  As you said, this is not feasible within the Plex Framework. Sorry.

**Comment by pdille** [comment]
Understood. Thanks for the reply and of course many thanks for the hard work you and others on doing with this. It's definitely a must have Channel for Plex.
