### ISSUE TITLE
Error Message just started appearing

### ISSUE THREAD

**Issue by Pyxie** [piplongrun/lmwt-kiss.bundle#8]
Loaded up Primewire last night after not being home all day to receive the message:

>Error: www.primewire.ag is NOT a Valid Site URL for this channel.  Please pick a different site URL.

When attempting to change the Site URL on Preferences, the error is:
>No items to display.  This listing appears to be empty.

Help, please?

**Comment by scott20j** [comment]
I am not positive if piplongruns version has it but check settings if his
has the setting you will have a drop down to select a different site like
.org etc

**Comment by Twoure** [comment]
@Pyxie 
Get it resolved?

@scott20j 
Yes @piplongrun's version has the drop down menu to select a different host site.

**Comment by Pyxie** [comment]
@scott20j @Twoure 

Yes, thank you, it's working again.  Thanks!

**Comment by scott20j** [comment]
Thanks! I thought it did but wasn't positive. I will make note of it.

**Comment by Pyxie** [comment]
Hi Guys - Commenting here as I ran into the same issue again.
I attempted to change the URL and that failed for every URL on the list.  So I took a look at the DefaultPrefs.json - this bit here: 
```
{
		"id": "custom_url",
		"type": "bool",
		"label": "Use Custom Site URL",
		"default": "True"
	},
```
Default was set to "False" - changed it to true and it immediately worked again.  I have no idea WTF I'm doing so hopefully one of you guys know what I did and why it worked, lol.  

Thanks!

**Comment by Twoure** [comment]
@Pyxie 

You should have been able to _tick_ the **Use Custom Site URL** from within this channel's preferences to use the URL within **Custom Site URL**.

**Note:** the example _Custom Site URL_ below does not work within Plex's Framework.

![](http://i.imgur.com/fAlsF4a.png)

**Comment by Pyxie** [comment]
@Twoure 
My interface looks nothing like that.  See attached files.  the Prefs image shows what my Prefs on the Primewire Channel looks like, while the other shows what happens if I touch it in any way.  
![plex-primewire-prefs](https://cloud.githubusercontent.com/assets/8535189/18510649/c7b2f0e8-7a44-11e6-867d-77e20ab59228.JPG)
![plex-primewire-prefs-results](https://cloud.githubusercontent.com/assets/8535189/18510650/cc492514-7a44-11e6-9302-5c5a263d471b.JPG)

**Comment by Twoure** [comment]
Correct, your using PMP _(or a smart TV)_ client which doesn't official support displaying channel preferences. That interface is a work around.

My directions above are for the Plex Web Client.
